<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.0</version>
        <relativePath/>
    </parent>

    <groupId>be.vdab</groupId>
    <artifactId>logguard-ai</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>logguard-ai</name>
    <description>AI-driven error detection and analysis on OpenSearch logs</description>

    <modules>
        <module>logguard-core</module>
        <module>logguard-demo-app</module>
    </modules>

    <properties>
        <java.version>25</java.version>
        <opensearch.version>3.0.0</opensearch.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.opensearch.client</groupId>
                <artifactId>opensearch-java</artifactId>
                <version>${opensearch.version}</version>
            </dependency>
            <dependency>
                <groupId>org.opensearch.client</groupId>
                <artifactId>opensearch-rest-client</artifactId>
                <version>${opensearch.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
