-- LogGuard poll cursor + degradation state. Holds exactly one row (the singleton checkpoint).
-- Degradation columns are unused until Story 2.6 but created now (architecture lists only V1 for this table).
CREATE TABLE poll_checkpoint (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_successful_poll_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    degradation_started_at    TIMESTAMP WITH TIME ZONE,
    consecutive_poll_failures INTEGER NOT NULL DEFAULT 0
);
