-- One row per active error fingerprint (FR-8). Records expire after logguard.deduplication-window
-- (24h default); an encounter after expiry is treated as new. The fingerprint columns are denormalised
-- copies of ErrorFingerprint; fingerprint_hash is the lookup key (SHA-256 → first 8 hex, Story 4.1).
CREATE TABLE deduplication_record (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint_hash        VARCHAR(64) NOT NULL UNIQUE,
    exception_type          VARCHAR(512),
    throwing_method         VARCHAR(512),
    stack_trace_sequence    CLOB,
    first_seen_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    occurrence_count        INTEGER NOT NULL DEFAULT 1,
    last_notified_threshold INTEGER,
    wont_fix                BOOLEAN NOT NULL DEFAULT FALSE,
    stored_analysis         CLOB
);
